//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub mod prelude;

pub mod auth_group;
pub mod auth_group_permissions;
pub mod auth_permission;
pub mod auth_user;
pub mod auth_user_groups;
pub mod auth_user_user_permissions;
pub mod django_admin_log;
pub mod django_content_type;
pub mod django_migrations;
pub mod django_session;
pub mod polls_choice;
pub mod polls_question;
pub mod polls_user;
pub mod post;
