//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "polls_question")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub question_text: String,
    pub pub_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::polls_choice::Entity")]
    PollsChoice,
}

impl Related<super::polls_choice::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PollsChoice.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
